### ISSUE TITLE
test-complex-table

### ISSUE THREAD

**Issue by danse** [atorin/pandoc-test#10]

**Comment by danse** [comment]
this is pending on jgm/pandoc-types#36 but i tried a version of pandoc using that branch and it does not seem to help here, it might even make things worse. i want to run pandoc tests using that branch of the types

**Comment by danse** [comment]
@atorin la tabella in questo caso ha una formattazione particolare. sto lavorando per eliminare gli errori di sintassi e far sì che non venga omesso contenuto, ma l'effetto dell'indentazione come puoi immaginare va perso nella conversione. credi che ci saranno molti documenti che includono tabelle simili? vale la pena di immaginare delle soluzioni per ridurre gli aggiustamenti da fare manualmente?

**Comment by alterat** [comment]
@danse 
Ci sono probabilmente tanti modi per risolvere questo problema. Avere eliminato gli errori di sintassi è un ottimo punto di partenza. 
Quello che potresti valutare, se non l'hai già fatto, è come convertire tabelle con celle multiple. 
In particolare, vedi issue #21.

**Comment by danse** [comment]
hai decisamente centrato il problema, qui celle che spaziano su diverse colonne sono usate per l'indentatura, ma questo tipo di celle non sono supportate da pandoc.

un miglioramento che mi viene in mente è quello di spostare le celle di riempimento all'inizio, piuttosto che alla fine, di ogni riga. in questo modo l'allineamento avrebbe un senso. potrei scrivere un filtro che sposti le celle vuote da fine riga ad inizio riga, questo ridurrebbe il numero di cambiamenti manuali da fare ma non è un granché di miglioria per questo ti chiedo se i documenti simili sono molti. in ogni caso vorrei dare un'occhiata a tali documenti per capire cosa si può fare. un filtro che sposti le celle vuote all'inizio potrebbe creare più problemi che altro su alcuni documenti

**Comment by danse** [comment]
chiudo come d'accordo, il problema delle celle multiple verrà sviluppato in #21
