### ISSUE TITLE
Come formattare codice PDF?

### ISSUE THREAD

**Issue by danse** [atorin/pandoc-test#14]
Come deve essere formattato il codice per essere definito tale? Se parto da un PDF, come faccio a distinguere pezzi di codice dal corpo del testo?

**Comment by danse** [comment]
@atorin se serve posso leggere il codice di parsing da PDF e dirti cosa viene interpretato come codice, o possiamo fare un piccolo esperimento. Mi chiedo però a che serva, sicuramente non andrai a modificare nessun PDF. immagino che, se si può modificare qualcosa, va fatto prima che il PDF sia generato?

**Comment by alterat** [comment]
@danse 
Per darti un po' di contesto, i documenti di partenza possono essere sia PDF che DOCX, non sappiamo ancora in quale proporzione. 
Per i documenti PDF, dato che pandoc non supporta direttamente la conversione verso RST, bisogna necessariamente passare per un formato intermedio. La prima scelta è ovviamente il passaggio `PDF -> DOCX -> RST`, ma non è detto che questa sia la soluzione migliore. 
Anche per fare questa prima conversione (`PDF -> DOCX`), io ho usato Adobe Acrobat, ma non è detto che sia la soluzione più efficiente. 

Detto questo, sarebbe utile sapere in che modo queste informazioni sono rappresentate nel PDF, ma credo ci sia parecchio lavoro da fare: https://stackoverflow.com/a/6562443

**Comment by danse** [comment]
ah, sono sorpreso dal fatto che pandoc non legga i PDF. potremmo aggiungere un supporto almeno parziale ma credo che sarebbe un lavoro di due o tre mesi, da valutare. quindi la domanda qui è _come formattare codice in un DOCX?_, giusto? quindi questa issue duplica #5

**Comment by alterat** [comment]
Sì, direi che questa duplica #5.
