### ISSUE TITLE
Test4, errori nei link

### ISSUE THREAD

**Issue by alterat** [atorin/pandoc-test#19]
È possibile capire come mai i link all'inizio del documento vengono spezzati?

**Comment by danse** [comment]
da quel che vedo i link sono spezzati anche nell'originale. quel che succede inoltre è che dopo la traduzione i link vengono mostrati come markup RST e non vengono tradotti come link da `rst2html`. questo è dovuto a #12 ed ho verificato che la soluzione proposta per #12 risolve il problema anche in questo caso
