### ISSUE TITLE
test-code

### ISSUE THREAD

**Issue by danse** [atorin/pandoc-test#5]
@atorin dalla descrizione, questo sembra uno dei problemi più gravi ma non trovo il file corrispondente (qualcosa del tipo `input/code-test.docx`) in questo repo

**Comment by alterat** [comment]
Dovrebbe essere questo: https://github.com/atorin/pandoc-test/blob/master/input/code-test.docx

**Comment by danse** [comment]
haha che scemo non l'ho visto! forse un :coffee: sarebbe opportuno. grazie! :)

**Comment by danse** [comment]
renamed according to the change i'm proposing via pull request

**Comment by danse** [comment]
nel documento DOCX corrispondente a questo errore non sembra esserci nessuna formattazione che possa essere interpretata come codice. quando apro il documento con libreoffice il template XML che si vorrebbe tradotto come codice mi risulta essere semplice testo con default style e allineato a sinistra. viene usato un carattere a spaziatura fissa ma non credo pandoc analizzi i font per determinare cosa é codice

**Comment by alterat** [comment]
Grazie per il commento! 

Hai ragione, non possiamo aspettarci che pandoc riconosca del codice che non è esplicitamente marcato come tale. Quindi potremmo chiudere questa issue.

D'altro canto, però, se voglio che il codice venga convertito automaticamente, che tipo di formattazione devo usare nel testo .docx o .odt di partenza?

**Comment by danse** [comment]
> D'altro canto, però, se voglio che il codice venga convertito automaticamente, che tipo di formattazione devo usare nel testo .docx o .odt di partenza?

non mi é immediato capirlo leggendo il codice, farò un'esperimento scrivendo un blocco di codice in RST, traducendolo in DOCX ed ispezionandolo con openoffice

**Comment by danse** [comment]
come puoi vedere nella pull request, ho aggiunto i risultati del test e sembra che, almeno per quel che riguarda libreoffice, ci sia uno stile apposito per "source code". puoi ispezionare il DOCX generato con la tua versione di office per verificare che sia così anche nel tuo caso

**Comment by alterat** [comment]
@danse 
Nella mia versione di Word (15.27, Word 2016) il codice nel file **code.docx** non appare segnalato come tale in alcun modo, a parte per l'uso di un font diverso. 
In LibreOffice, invece, riesco a selezionare la tipologia "Source code" di paragrafo. 

Secondo me il problema della conversione del codice nei testi è piuttosto spinoso. Vedo almeno due ordini di problemi:

1. Da un lato come deve essere formattato il codice per essere definito tale? Se parto da un PDF, come faccio a distinguere pezzi di codice dal corpo del testo?

2. Una volta stabilito il formato di partenza, come fa pandoc a riprodurre un codice (per esempio, XML) con i rientri adeguati? Al momento, pandoc produce un output del tipo
```
::

   codice tutto su un'unica riga
```

In realtà dovrebbe usare la direttiva `.. code-block::`, ma questo richiede di conoscere il linguaggio in cui è scritto il codice.

Data la complessità del problema, terrei al momento in stand-by e attaccherei questo problema all'inizio di *batch 2* se sei d'accordo.

**Comment by danse** [comment]
non so se e quando ci sarà un batch 2. direi di non farci guidare solo dalla difficoltà del problema ma anche dall'impatto che questo ha sui nostri obiettivi. da quel che ho capito scrivete molta documentazione tecnica dove è facile che ci sia del codice, quindi credo abbia senso fare il possibile per facilitare questo caso d'uso.

ho dedicato le issue #14 e #15 alle tue domande in modo da discutere i vari aspetti senza accavallarci. riguardo questa issue, magari possiamo usarla per discutere come marcare del codice con Word. mi sorprenderebbe se non ci fosse un modo facile per farlo, ma al momento non posso far altro che cercare nel web perché non uso windows ed testare con una macchina virtuale sarebbe lento

**Comment by danse** [comment]
possiamo considerare chiusa questa issue?

**Comment by alterat** [comment]
Sì, abbiamo trasferito la discussione tecnica alla #14 e #15.
